### ISSUE TITLE
Way to figure out size of spm in memory?

### ISSUE THREAD

**Issue by PeteHaitch** [wrathematics/float#1]
Say in the example in the README, is there a way to figure out the size of the _spm_, `xs`, is using in memory? A little helper function would be cool and appreciated as I bumble around trying to understand how this works.

**Comment by wrathematics** [comment]
Great suggestion! Generally it will be half that of its double precision counter part, but there will be some small differences based on metadata.

I've added an `object.size()` method in the latest push:

```r
library(spm)
x = matrix(0, nrow=20000, ncol=2500)
s = fl(x)

object.size(x)
## 400000200 bytes
object.size(s)
## 200000024 bytes
```

**Comment by PeteHaitch** [comment]
Awesome, thanks!
