### ISSUE TITLE
Minor issue - printing with str()

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#12]
At the moment output is a bit confusing:
```r
set.seed(1)
str(fl(x = matrix(runif(12), 4)))
```
> Formal class 'float32' [package "float"] with 1 slot
  ..@ Data: int [1:4, 1:3] 1049096384 1052673798 1058186885 1063813198 1045333429 1063648478 1064425021 1059662347 1059130782 1031607194 ...

**Comment by wrathematics** [comment]
Ahh, good catch. I forgot to write a `str()` method. I'll try to add one tonight.

**Comment by wrathematics** [comment]
Added in https://github.com/wrathematics/float/commit/1f139a08606e1f260c4627e02b7b7f0b973aa80a.
