### ISSUE TITLE
Subsetting issue

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#13]
I've started to add `float` backend to some of my packages. So I believe I will discover some issues (and will report here). Here is first one:

```r
library(float)
m = fl(matrix(1:4, 2, 2))
m[m < 2] = 0
```

>Error in `[<-`(`*tmp*`, i, j, value = value) : 
>  (subscript) logical subscript too long

However this is valid in base R.

**Comment by wrathematics** [comment]
I really appreciate the reports! Should be fixed by https://github.com/wrathematics/float/commit/ce27ad3f3222786f76f9b432d61626956c8c66cc
