### ISSUE TITLE
dimnames()

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#14]
```r
library(float)
m = fl(matrix(1:4, 2, 2))
dimnames(m) = list(NULL, NULL)
```
> Error in dimnames(m) = list(NULL, NULL) : 'dimnames' applied to non-array

**Comment by wrathematics** [comment]
I haven't really built in any support for row/column names so far. I'll try to take a crack this weekend.

**Comment by wrathematics** [comment]
Sorry it took me so long to get to this. Should be fixed in https://github.com/wrathematics/float/commit/d3790130b4c972a565714f5384748803d2bd6294.
