### ISSUE TITLE
Integer overflow somewhere

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#17]
I'm trying to create float matrix from integer representation and getting:
> Error in if (len > 1) paste(len, " elements, ", sep = "") else "" : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In nrow(x) * ncol(x) : NAs produced by integer overflow

It seems it calculates size of array internally and it fails when it exceeds max int.

Simple reproducible example:
```r
m = matrix(0L, 620000, 4096)
m = float32(m)
```

**Comment by wrathematics** [comment]
I haven't been able to replicate this so far:

```r
library(float)
m = matrix(0L, 620000, 4096)
m = float32(m)
m
## # A float32 matrix: 620000x4096
##       [,1] [,2] [,3] [,4] [,5]
##  [1,]    0    0    0    0    0
##  [2,]    0    0    0    0    0
##  [3,]    0    0    0    0    0
##  [4,]    0    0    0    0    0
##  [5,]    0    0    0    0    0
##  [6,]    0    0    0    0    0
##  [7,]    0    0    0    0    0
##  [8,]    0    0    0    0    0
##  [9,]    0    0    0    0    0
## [10,]    0    0    0    0    0
## # ...
```
The only nrow*ncol call is in the `length()` getter, which shouldn't be relevant here (and should just promote to a double automatically). I see some possible type issues in the src/ tree that could be related, but nothing super obvious. It might be useful to see this in full context (as opposed to a minimal example), as there may be something else going on.

**Comment by dselivanov** [comment]
Update - this error occurs in Rstudio IDE, but not in console. So I believe it could related to their viewer pane. 
Mb this is also related to `str()` call. Because when I call `str(m)` in console I get:

```r
str(m)
#Error in 1:(min(length(object), MAXLEN)) : NA/NaN argument
#In addition: Warning message:
#In nrow(x) * ncol(x) : NAs produced by integer overflow
> sessionInfo()
#R version 3.4.2 (2017-09-28)
#Platform: x86_64-apple-darwin16.7.0 (64-bit)
#Running under: macOS High Sierra 10.13.2
#Matrix products: default
#BLAS: #/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#LAPACK: #/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
#locale:
#[1] en_US.UTF-8/UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     
#other attached packages:
#[1] float_0.1-2
#loaded via a namespace (and not attached):
#[1] compiler_3.4.2
```

**Comment by PeteHaitch** [comment]
Fwiw I'm pretty sure RStudio viewer pane simply calls `str()`

**Comment by wrathematics** [comment]
Aha! You two are the best! I believe it should be fixed now.

**Comment by dselivanov** [comment]
confirm - works perfectly
