### ISSUE TITLE
Error when subsetting matrix with dimnames

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#18]
`float` is latest from github.

```r
m = matrix(1, 10, 10, dimnames = list(letters[1:10], NULL))
library(float)
m_fl = fl(m)
m_fl[1:5, ]
```
> Error in dimnames(d) = dimnames(x) :
>   length of 'dimnames' [1] not equal to array extent

**Comment by wrathematics** [comment]
Thanks, should be fixed in https://github.com/wrathematics/float/commit/811e5e77cbe1c406578ef99d55edf95e4d7a72ac.
