### ISSUE TITLE
`ldflags` gives incorrect arguments when path has spaces

### ISSUE THREAD

**Issue by david-cortes** [wrathematics/float#45]
From https://github.com/david-cortes/MatrixExtra/issues/5

Calling `float:::ldflags(static=TRUE)` on a system in which the R installation path contains spaces will produce an invalid path as it won't add quotation marks around it.

**Comment by wrathematics** [comment]
Sorry for the delay. Should be fixed now.

**Comment by david-cortes** [comment]
Thanks for fixing. However, I think it would now fail if the path contains double quotes, which would need to be escaped.

**Comment by david-cortes** [comment]
@wrathematics While this worked on linux, I think it's now causing issues linking in both windows and mac. See for example this error from winbuilder (temporary link):
https://win-builder.r-project.org/XSj6J2hE7NBc/00install.out
```
g++ -std=gnu++17 -shared -s -static-libgcc -o recometrics.dll recometrics-win.def RcppExports.o Rwrapper.o -fopenmp -LD:/RCompile/recent/R/bin/x64 -lRblas -lgfortran -lm -lquadmath "D:/RCompile/CRANguest/R-devel/lib/float/libs/x64/libfloat.a" -llapack -lblas -Ld:/rtools43/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools43/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R/bin/x64 -lR
D:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find "D:/RCompile/CRANguest/R-devel/lib/float/libs/x64/libfloat.a": Invalid argument
```

And from mac m1:
https://www.stats.ox.ac.uk/pub/bdr/M1mac/recometrics.log
```
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Users/ripley/R/R-devel/lib -L/opt/R/arm64/lib -o recometrics.so RcppExports.o Rwrapper.o -L/Users/ripley/R/R-devel/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath "/Users/ripley/R/Library/float/libs/libfloat.a" -llapack -lblas -L/Users/ripley/R/R-devel/lib -lR -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '"/Users/ripley/R/Library/float/libs/libfloat.a"'
```

**Comment by wrathematics** [comment]
Will take a look tonight. I don't have access to Windows or Mac, so I can't really test this. Quick thought is to just revert to the old behavior for Windows/Mac exclusively. What do you think?

**Comment by david-cortes** [comment]
Thanks for the quick answer. I think it'd make sense to do so. I did some experiments and for me:

* Quotes in paths worked fine on windows, but CRAN still complains about it so don't think any other solution would do.
* Quotes didn't work on mac, but what worked instead was to add backslashes to every space and double quote - e.g. `a path` -> `a\ path`; `mid"dle` -> `mid\"dle`. Not sure if that would work on CRAN though, and not sure if those two are the only symbols that need escaping.
