### ISSUE TITLE
Bug in eigen() and svd() on 32-bit Windows

### ISSUE THREAD

**Issue by wrathematics** [wrathematics/float#6]
Setup:

```r
library(float)
set.seed(1234)
s = flrnorm(10, 3) # 10x3 float matrix

La.svd(s, nu=0, nv=0)
```

On everything but 32-bit Windows, I see:

```
$d
# A float32 vector: 3
[1] 3.412601 3.192742 2.107736
```

On 32-bit Windows, I see:

```
$d
# A float32 vector: 3
[1] NaN NaN NaN
```

This causes `tests/svd.r` and `tests/norm.r` to fail.

There is a reverse but possibly related problem for eigenvalues:

```r
cp = crossprod(s)

eigen(cp, symmetric=TRUE, only.values=FALSE)
```

As before, most platforms give:

```
$values
# A float32 vector: 3
[1] 11.645850 10.193604  4.442551

$vectors
# A float32 matrix: 3x3
            [,1]       [,2]      [,3]
[1,]  0.75543672 -0.5654903 0.3309623
[2,] -0.64987493 -0.7110580 0.2684381
[3,] -0.08353428  0.4178721 0.9046574
```

while 32-bit Windows gives garbage values for the eigenvectors (whatever the os feels like using for uninitialized values), but it gives `7.594929` for each of the eigenvalues.

**Comment by wrathematics** [comment]
I am completely stumped on this and have exhausted 100% of my Windows knowledge trying to track it down. It's either something really obvious I can't see for some reason, or this is hard.

@snoweye would you be willing to help? I totally understand if you're busy and can't.

**Comment by snoweye** [comment]
I did not see this message. I will check.

**Comment by wrathematics** [comment]
It only shows up in winbuilder. Didn't show up in my VM or in rhub's Windows machine.

**Comment by wrathematics** [comment]
Wait, scratch that. It breaks on rhub too...

**Comment by snoweye** [comment]
[This](https://github.com/wrathematics/float/pull/10) should fix/avoid the problem.
