### ISSUE TITLE
warnings about failed vectorization

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#7]
Just FYI (compiled with clang 4.0):

> scale.c:19:3: warning: loop not vectorized: failed explicitly specified loop vectorization [-Wpass-failed]
>  for (len_t i=0; i<m; i++)

> eigen.c:13:3: warning: loop not vectorized: failed explicitly specified loop vectorization [-Wpass-failed]
>  for (len_t i=0; i<len/2; i++)

**Comment by wrathematics** [comment]
Thanks, I'll look into it.

**Comment by wrathematics** [comment]
The compiler was right! Should be fixed in the latest.
